"""
sharp-momentum-means-everywhere_svg_doodles.py  (AUTO-GENERATED by svg_doodles.py)
SVG-icon animations for the doodle sections of "Why a Sharp-Momentum Particle Must Be Everywhere at Once".
Each beat is its own Scene -> its own clip; overlay a doodle on top or cut in Premiere.

Render (all clips):
    manim -t -qh sharp-momentum-means-everywhere_svg_doodles.py IntroSVG H01SVG OutroSVG
"""
from pathlib import Path
from manim import *

INK = "#1a1a1a"
ACCENT = "#5A5653"
FONT = "Shadows Into Light"
TITLE = 'Why a Sharp-Momentum Particle Must Be Everywhere at Once'
ICONS = {'H01': '/sessions/nifty-cool-ritchie/mnt/Cowork/Manim/shared/svg/4585701-arrows-and-infographic-elements-001-arrow.svg'}
DUR = {'INTRO': 5.46, 'H01': 4.6, 'OUTRO': 10.21}


def _icon(beat_id, height=3.0):
    m = SVGMobject(ICONS[beat_id])
    m.set_stroke(INK, width=3).set_fill(ACCENT, opacity=1.0)
    m.scale_to_fit_height(height)
    return m


class _Base(Scene):
    beat_id = "INTRO"
    show_title = False        # intro/outro: title text. hooks: icon only.

    def construct(self):
        self.camera.background_color = WHITE
        t = DUR.get(self.beat_id, 4.0)
        has_icon = self.beat_id in ICONS
        used = 0.0
        if has_icon:
            icon = _icon(self.beat_id)
            icon.move_to([0, 0.4 if self.show_title else 0, 0])
            dt = min(2.0, t * 0.55)
            self.play(DrawBorderThenFill(icon), run_time=dt)
            used += dt
        if self.show_title:
            ttl = Text(TITLE, font=FONT, font_size=30, color=INK)
            ttl.scale_to_fit_width(min(11.0, ttl.width))
            ttl.to_edge(DOWN, buff=0.6) if has_icon else ttl.move_to(ORIGIN)
            dt = min(1.4, t * 0.3)
            self.play(Write(ttl), run_time=dt)
            used += dt
        self.wait(max(0.3, t - used))

class IntroSVG(_Base):
    beat_id = 'INTRO'
    show_title = True

class H01SVG(_Base):
    beat_id = 'H01'
    show_title = False

class OutroSVG(_Base):
    beat_id = 'OUTRO'
    show_title = True

