// theme.ts — OVERLAY look (generated by muzak-overlay scaffold).
//
// This project overlays a karaoke lyric layer + audiogram waveform on top of an
// EXISTING finished video (source.mp4). The background gradient / generated-media
// machinery from the full muzak pipeline is intentionally absent — the video is
// the background. Mechanical components read ONLY from here.
//
// Tuned for legibility over arbitrary footage: bright warm-white waveform, white
// karaoke text with a heavy shadow, a gold accent on the chorus ("Strange
// brothers"), and the lyric/waveform band centered vertically over the footage.
export const theme = {
  // palette — chosen for contrast over a dark, war-themed AI video (G minor).
  background: "#000000",
  accent: "#F2EEE4",      // waveform stroke: warm white, reads over most footage
  accent2: "#E0B15E",     // chorus / hook color: amber gold
  accentWarm: "#D9A066",
  textColor: "#FFFFFF",
  flashColor: "#FFFFFF",
  flashMax: 0.2,
  beatScalePulseMax: 1.12,   // gentle; the footage already carries motion

  // motion vocabulary (from BPM ~143.6)
  easingCharacter: "snappy",
  springDamping: 9,
  springStiffness: 210,

  // type
  fontFamily: "Inter, system-ui, sans-serif",
  lyricSize: 58,
  hookSize: 92,
  fontWeight: 800,
  lyricStyle: "karaoke",       // per-word highlight (true karaoke when forced-aligned)
  lyricInFrames: 8,
  lyricOutFrames: 6,
  readableHoldFrames: 18,

  // visualizer: "audiogram" = dense oscilloscope waveform across the whole video
  visualizerType: "audiogram",
  spectrumSamples: 64,
  spectrumMaxHeight: 200,
  waveformStroke: 3,
  // audiogram band: vertical centerline + height (fractions of frame height).
  // The lyrics center ON this line, so moving it moves the lyrics too. Default 0.8
  // = lower third — keeps the band out of faces/action in real footage. Use ~0.5
  // for a centered "visualizer" feel on abstract/empty backgrounds.
  waveformMid: 0.8,
  waveformAmp: 0.12,

  // scrim: a soft dark band centered on waveformMid so text stays legible over
  // bright/busy footage. height = fraction of frame; opacity = peak darkness.
  scrimHeight: 0.4,
  scrimOpacity: 0.5,

  // unused over video (kept so shared components compile)
  bgHueRange: [0, 0] as [number, number],
  bgSat: 0,
  bgLumRange: [0, 0] as [number, number],
};
