"""
energy-levels-arent-evenly-spaced_svg_doodles.py  (AUTO-GENERATED by svg_doodles.py)
SVG-icon animations for the doodle sections of "Why Quantum Energy Levels Aren't Evenly Spaced".
Each beat is its own Scene -> its own clip; overlay a doodle on top or cut in Premiere.

Render (all clips):
    manim -qh energy-levels-arent-evenly-spaced_svg_doodles.py IntroSVG H01SVG H02SVG OutroSVG
"""
from pathlib import Path
from manim import *

INK = "#1a1a1a"
ACCENT = "#5A5653"
FONT = "Shadows Into Light"
TITLE = "Why Quantum Energy Levels Aren't Evenly Spaced"
ICONS = {'INTRO': '/sessions/nifty-cool-ritchie/mnt/Codex/Manim/shared/svg/4630889-cosy-creatures-002-bear.svg', 'H01': '/sessions/nifty-cool-ritchie/mnt/Codex/Manim/shared/svg/4511875-strategy-018-ladder.svg', 'H02': '/sessions/nifty-cool-ritchie/mnt/Codex/Manim/shared/svg/4511875-strategy-018-ladder.svg', 'OUTRO': '/sessions/nifty-cool-ritchie/mnt/Codex/Manim/shared/svg/4630889-cosy-creatures-002-bear.svg'}
DUR = {'INTRO': 4.08, 'H01': 4.41, 'H02': 3.24, 'OUTRO': 8.2}


def _icon(beat_id, height=3.0):
    m = SVGMobject(ICONS[beat_id])
    m.set_stroke(INK, width=3).set_fill(ACCENT, opacity=1.0)
    m.scale_to_fit_height(height)
    return m


class _Base(Scene):
    beat_id = "INTRO"
    caption = ""
    show_title = False

    def construct(self):
        self.camera.background_color = WHITE
        t = DUR.get(self.beat_id, 4.0)
        icon = _icon(self.beat_id)
        icon.move_to([0, 0.4 if (self.caption or self.show_title) else 0, 0])
        self.play(DrawBorderThenFill(icon), run_time=min(2.0, t * 0.55))
        extras = []
        if self.show_title:
            ttl = Text(TITLE, font=FONT, font_size=30, color=INK)
            ttl.scale_to_fit_width(min(11.0, ttl.width)).to_edge(DOWN, buff=0.6)
            extras.append(ttl)
        elif self.caption:
            cap = Text(self.caption, font=FONT, font_size=30, color=INK)
            cap.scale_to_fit_width(min(11.0, cap.width)).to_edge(DOWN, buff=0.6)
            extras.append(cap)
        if extras:
            self.play(*[Write(e) for e in extras], run_time=min(1.2, t * 0.25))
        self.wait(max(0.3, t - min(2.0, t * 0.55) - min(1.2, t * 0.25)))

class IntroSVG(_Base):
    beat_id = 'INTRO'
    caption = ''
    show_title = True

class H01SVG(_Base):
    beat_id = 'H01'
    caption = 'a person climbing an'
    show_title = False

class H02SVG(_Base):
    beat_id = 'H02'
    caption = 'the person on a'
    show_title = False

class OutroSVG(_Base):
    beat_id = 'OUTRO'
    caption = ''
    show_title = True

